<a href="https://colab.research.google.com/github/gulnajmm/Python_Learning/blob/main/numpy_assignemnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#assignment
#create 4*4 array of all True values
#create 4*4 array of all false values
#create 4*4 array of Digonal elemnet as 1s and non diagonal as 0s
#create 4*4 array of Diagonal as True ad non diagonal as false
#create 4*4 array of diagonal as false and non diagonal as true


In [ ]:
np.zeros(6,dtype=bool)

array([False, False, False, False, False, False])

In [ ]:
#create 4*4 array of all True values
np.full((4,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#create 4*4 array of all false values
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#create 4*4 array of Digonal elemnet as 1s and non diagonal as 0s
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#create 4*4 array of Diagonal as True ad non diagonal as false
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
#create 4*4 array of diagonal as false and non diagonal as true
~np.eye(4,dtype =bool)


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])