<a href="https://colab.research.google.com/github/gulnajmm/Python_Learning/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import library
import numpy as np

In [2]:
#check the version
np.__version__

'2.1.3'

IMP Qestion - create numpy array

In [3]:
#manual way
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [ ]:
#numpy is for numbers not for char

In [ ]:
#Q .what is difference between list and numpy array
#List is built in data type in python and NUmpy is ext library


# Different ways to create a numpy array

In [5]:
#arange() --> it is a range not arrange be careful --i is same as range() in python
np.arange(11) #(stop)--> exclusive


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,7) #(start,stop)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.arange(1,11,2) #start stop and step

array([1, 3, 5, 7, 9])

In [8]:
#user zeros() to create as array of all zeros
np.zeros(10)  #here it will create array of 10 zeros -- here we have default float dtype.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#above array  is 1D array -change dtype to int
np.zeros(5,dtype =int)

array([0, 0, 0, 0, 0])

In [12]:
np.twos(10) #in numpy only 2 values zeros and ones

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [14]:
np.zeros(6,dtype=bool)

array([False, False, False, False, False, False])

In [15]:
np.zeros(6,dtype=str)

array(['', '', '', '', '', ''], dtype='<U1')

In [16]:
np.zeros(6,dtype=float)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(6,dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [18]:
b = np.zeros(6,dtype=int)
b

array([0, 0, 0, 0, 0, 0])

In [19]:
#check dimention of array whether it is 1 D or 2D
b.ndim

1

In [ ]:
#1D -means collection of element(rows)
#2D -means collection of(row and column)
#3D -means collection of (block,row,column)

In [21]:
#2D
c=np.zeros((4,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
c.ndim

2

In [ ]:
c.ndim()

In [23]:
#3D (4block,2 rows,2column)
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
#Assignment create 2D and 3D array of ones

In [24]:
#create an array  of constant numbers
#np.full(shape,fill_value)
np.full((3,3),-1) #3 rows 3column with -1 value

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
#assignment
#create 4*4 array of all True values
#create 4*4 array of all false values
#create 4*4 array of Digonal elemnet as 1s and non diagonal as 0s
#create 4*4 array of Diagonal as True ad non diagonal as false
#create 4*4 array of diagonal as false and non diagonal as true


In [25]:
np.zeros(6,dtype=bool)

array([False, False, False, False, False, False])

In [27]:
#create 4*4 array of all True values
np.full((4,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
#create 4*4 array of all false values
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
#create 4*4 array of Digonal elemnet as 1s and non diagonal as 0s
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
#create 4*4 array of Diagonal as True ad non diagonal as false
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [34]:
#create 4*4 array of diagonal as false and non diagonal as true
~np.eye(4,dtype =bool)


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])